baseURL = 'https://samsobjectfinder.com/'
languageCode = 'en-us'
title = 'Sams DayZ Object Finder'
theme = 'ananke'

relativeURLs = false
canonifyURLs = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true