baseURL = 'https://samgeekman.github.io/samsdayzobjectfinder/'
languageCode = 'en-us'
title = 'Sams DayZ Object Finder'
theme = 'ananke'

relativeURLs = true
canonifyURLs = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true